### ISSUE TITLE
running on custom dataset

### ISSUE THREAD

**Issue by andreaceruti** [cvlab-epfl/mot3d#1]
Hi! I have recently seen your work.
I am looking for an OFFLINE tracking-by-detection MOT algorithm and It seems that your work match with my problem.
In my case I am applying a detector (maskrcnn) to detect multiple instances of grape bunch in a video.
So basically I am dividing the video in different frames and then I apply the detector to each frame and I save the instances found(bounding boxes) in a json file.
Now I would like to apply your algorithm but I have some difficulties in understanding how I should apply the procedure.

I have tried SORT for example and there I had to pass to the kalman filter an array composed as bounding boxes + score of the bounding box produced by the detector.
1)Why in your method this score is not considered?

2)How would I pass my detections to your method? I have to calculate the centroid of each bounding box and pass (x,y) as in your examples?

3)How do I retrieve the tracklet, and so the ID of each original instance at the end of the procedure? Running your examples I can produce the graphs, but IF you can help me I would like to retrieve for each instance an ID for the tracklet so at the end I can visualize this ID on my images as in this case

<img src="https://user-images.githubusercontent.com/44469014/168613991-45d17bed-3f0f-4b5d-bb9b-29d9405e54b1.png" alt="example image" width="500" height="700">

**Comment by lcit** [comment]
Hello, the example [simple_2d](https://github.com/cvlab-epfl/mot3d/blob/master/examples/simple_2d/example.py) is straightforward. You have to first create the list of objects of type detections (i.e `Detection2D` if you want to track in the image space), then provide the functions that generate the weights for the flow graph `weight_distance` and `weight_confidence`, then build the graph and solve it.

The detection object takes different parameters such as the index of the frame `index` (if you have a video of 100 frames,  the index ranges from 0 to 99), the position of the detected object `position` (in your case you can take the center of the bounding box), the confidence of the detection `confidence` (I suggest you discard all the boxes that have a score lower than 0.75 and set `confidence=1`), `bbox` (xmin, ymin, xmax, ymax) the coordinate of the bounding box (this is used to compute an additional similarity weight. You can use this if you know your bounding boxes are not jittering. Otherwise disable it with`use_bbox=Falese`), or also `color_histogram` which is a feature vector you can use to compute an additional similarity weight (in your case is not very useful since all grapes look the same).

In the weight function you have to make sure you set `max_distance` correctly which is the maximum allowed distance between two detections (it is defined in pixels if you are working on the image space). And, `sigma_distance` which is the sigma of the gaussian defining the magnitude of the weights. Then play a bit with the parameter to understand what they do or have  alook at the documentation in the repo.

The solution is then stored in `trajectories` which is a list of lists of objects of type Detection.

**Comment by andreaceruti** [comment]
@lcit Thank you for the clear explanation! Your reply was very helpful. Before I was giving as input bbox=[xmin, xmax, width, height] as bounding box and also other wrong stuff.  

I have succesfully managed to run both simple_2d and simple_2d_tracklets scripts with my custom detection, I have noticed that there is also an id we can attach to each Detection2D that could be really useful when visualizing the tracklets/detection results back to the original image. 

I will also try the 3d example since I have rgb-d images and so I can insert the depth value for each detection, but before I will look in-depth for the documentations, thank you for your time!
