### ISSUE TITLE
Adding IoU between bounding box as weight function

### ISSUE THREAD

**Issue by andreaceruti** [cvlab-epfl/mot3d#2]
HI, I am using your project for the MOT part of my thesis and I would like to ask a few questions and some possibles how-to enhancement.

Firstly [this link](https://drive.google.com/drive/folders/1gIAJWXX1gZSi9zQEivmfZgTt7sa_q8IK?usp=sharing) is an example I am able to reproduce with your project, I am pretty satisfied with the result. I have read the annotations and played a bit with the parameters, but since I am not an expert there could be some parameter not properly tuned.
For my example I pass as positions the centroid of the detected bounding boxes, so they will be in image space (they will cover all the resolution, this is different from your example positions in 2d) 
And here the relevant parameters, the others are unused.
-weight distance:         sigma_jump=1, sigma_distance=10, sigma_box_size=0.3, max_distance=50, use_bbox=True
-first pass on detections:          detections, weight_source_sink=0.1,  max_jump=15
-split_trajectory_modulo:          length = 15
-remove short trajectories:        th_length = 5
-second pass on tracklets:        detections_tracklets, weight_source_sink=0.1, max_jump=15
Looking at my example, is there something I could do to enhance the result?

Another question that is central is how could I write a new weight function. If I have understand correctly I should write a new distance function and then insert the weight accorting to distance/sigma of distance function, but If you could elaborate a bit on this it would really help me. My idea is to add as similarity measure the [Intersection Over Union](https://pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/#:~:text=predicted%20bounding%20boxes.-,What%20is%20Intersection%20over%20Union%3F,the%20popular%20PASCAL%20VOC%20challenge.) (calculated both on bounding box and on segmentation mask). Maybe I am a bit too general on this and I would reopen another issue since I know that I am being too verbose.

Lastly I have done another example with my dataset following the 3d one provided, since for each centroid I have also the depth information, but differently from you for the depth I have the distance represented in meters (and so the magnitude is different with respect to the other 2 coordinates).
The example works but I am trying to tune its parameters, so how could I use for example the attribute "view2d" that is present in the "Detection3d" class? I can see that is a dictionary but I can't find documentation on how to fill this dictionary

**Comment by lcit** [comment]
Hi, passing the centroid of the detected bounding boxes is the intended way of using the library for bounding boxes. So it is correct. Regarding the parameters, they look ok to me. If you really want to optimize them I suggest running a grid search over them to find the optimal set.

To modify the weight function you have to first create a similarity function that returns 1 for perfect match and 0 otherwise. There are examples [here](https://github.com/cvlab-epfl/mot3d/blob/master/mot3d/distance_functions.py). Then you have to modify the weight function 'weight_distance_detections_2d' [here](https://github.com/cvlab-epfl/mot3d/blob/master/mot3d/weight_functions.py). This function computes different (one minus-) similarity scores and then pass them through a gaussian function to magnify or diminish their importance with the sigma parameter. The final weight that this function outputs is the product of all weights. That means that if one weight is close to zero the output of this function will be close to zero too.
Now regarding the IoU, since the camera is moving, you have little overlap between bounding boxes of the same. it would make sense to make a similarity function that i) computes the center of mass of the segmentation mask, ii) subtract this to align the boxes and then iii) compute the IoU.

For the 3D detection, would it be an ok solution to scale the depth so that you have the same resolution as in pixels?

**Comment by andreaceruti** [comment]
@lcit sorry for the late reponse, I was unable to work in these days.

Could you explain me the reason of why should I do this preprocessing before calculating the IoU? And if I have understand correctly do you mean that I should find the center of mass of the segmentation mask (for example as [this](https://stackoverflow.com/questions/65304623/calculating-the-center-of-mass-of-a-binary-image-opencv-python#:~:text=We%20can%20use,np.average(mass_y))), subtract it to the centroid found with the bounding box only to recalibrate the new bounding box, and then calculate the IoU with this new bounding box? This approach makes perfect sense to me but I am trying to understand well.

For the 3d detection I don't think the depth could be scaled in any way or I am not aware of how I could do it. The detection is done on the 2-D image only (RGB). So what I do is to take a bounding box centroid coordinates, then I look at the depth channel(grayscale image) to recover the depth value in that specific point. So for the 3-D centroid I have x,y of the image (for example I have that the centroid is at x=100, y=120 and the resolution of the image is 480x848) and the float value of depth in meters that goes from 0 to 6000 millimeters at max. So i think your depth is calculated in a different way with respect to mine.

**Comment by lcit** [comment]
The IoU computed on the segmentation masks is a good way to match shapes. In order to do that between two frames you want to compensate their motion. The easiest way is to compute the centre of the mask and then subtract it. This might no be very precise if the masks are too different but worth trying. Doing so for the IoU between bounding boxes would not be much different than simply using the distance between the center of the boxes which is already implemented.

If scaling the depth is not good enough you have to make some modifications to the weight function. You have to compute two distances, one in 2d and one along depth, and have two parameters for two different Gaussian functions. One for x and y-axis and one for the depth.
