### ISSUE TITLE
Why the exponential function for the time cost?

### ISSUE THREAD

**Issue by ricber** [cvlab-epfl/mot3d#3]
Hi, I was wondering why you chose the exponential function instead of the Gaussian for the time cost. For the rest of the costs (distance, color appearance, bbox) you used the Gaussian function.
For example, the distance cost is expressed as:
$$C_d(u,v) = -exp \left( \frac{-d^2}{\sigma_d^2} \right)$$
While the time cost is expressed as:
$$C_t(u,v) = -exp \left( -(\Delta t-1)\sigma_t \right)$$
Why is that? For a unit change in the value of distance (measured in pixels), the Gaussian distance cost changes faster than the exponential cost for a unit change in time (measured in number of frames). It seems that, in the total cost, you wanted to give more relevance to a unit change of distance instead of time. Is it correct, and if yes, why?

**Comment by lcit** [comment]
Hi, If I recall correctly, I chose the exponential to privilege even more the detections closer in time. This because, in general, the exponential has a steeper descent than the gaussian. If you have three detections where the furthest in time has an appearance and/or distance closer than the closest in time, a steeper descent in the time cost might allow still to pick the closest detections in time. 

This was working better in my projects but I cannot say that it generalizes well to different setups.

**Comment by ricber** [comment]
@lcit thank you for the reply! Indeed, I agree with you that it's a good idea to give a higher relevance to closer detections in time. I did some simple calculations and plotting to investigate the phenomenon better. It seems that the sigma has an effect on whether the exponential or the Gaussian is changing faster. Indeed, the Gaussian has the distance squared in the exponent, and it should thus change faster than the exponential for a unit change of distance and time. However, based on the sigma, there is a range in which the exponential changes faster than the Gaussian. I thus made some plots of the exponent value vs distance/time. 
For $\sigma_d=1, \sigma_t=1$, the exponent of the Gaussian is always changing faster, and so are the associated costs. Thus, detections farther in time but at a closer distance will be preferred (the opposite we would like). 
<img src="https://github.com/cvlab-epfl/mot3d/assets/18362950/f6e28978-eba6-488a-a2cb-eafbf8dbc098" width="500" height="300">
For $\sigma_d=3, \sigma_t=1$, there is a small range (until about 7 of distance/time) in which the time exponent changes faster.
<img src="https://github.com/cvlab-epfl/mot3d/assets/18362950/061952f7-4139-4904-8aff-8f1037bc142a" width="500" height="300">
For $\sigma_d=10, \sigma_t=1$, the range is even bigger, and in this range, detections closer in time will be preferred than detections closer in distance.
<img src="https://github.com/cvlab-epfl/mot3d/assets/18362950/178dfd95-9ebe-47b6-ade0-86bfa84a90fd" width="500" height="300">

Do you agree with my analysis, or do you see any problems?

**Comment by lcit** [comment]
There seems to be a problem with your plots. The two functions should be bounded in the range [0,1]. And in general, since the time is dictated by the frame count, the time range to consider is something in the range [0, 3]. You probably would never match detections that are 20 frames apart. Also keep in mind that the first detection has time $t=1$ this is why we have the -1 inside the exponential function.

But indeed different sigmas give different rates. It needs to be calibrated.

These are the plots I would expect (the not negated ones). The default parameters in the code are $\sigma_{d}=2$ and $\sigma_t=1$
![Screenshot 2023-10-08 at 14 13 27](https://github.com/cvlab-epfl/mot3d/assets/10977960/3ec6bda6-4d0e-48d1-998f-ec6949910692)

**Comment by ricber** [comment]
@lcit my plots were just showing the exponents, so $-d^2 / \sigma_d^2$ for the distance, and $-(\Delta t-1)\sigma_t$ for the time. I just wanted to show that, depending on sigma, the two exponents change with different rates in different ranges. The total powers will change with similar relative rates since we have the same base ($e$) for both exponents. Indeed, we can recognize the same behavior in your plots. If we take the two sigmas = 1, we see that the gaussian is decreasing faster from a time/distance > 1. This means that we will prefer detections closer in distance even if they are farther in time compared to others. The opposite happens with sigmas = 2. Now, the exponential is decreasing faster, and we have the desired behavior, that is, detections are preferred if close in time than in distance. 

I am also missing something from your graph. The minimum distance is 0 (when the two detections overlap), but the minimum delta time shouldn't be 1, that is, with detections in immediate successive frames? So, if $\Delta t = 1$, then $-(\Delta t-1)\sigma_t = 0$ and the exponential function is 1. So, why your exponential function is 1 at time 0 and not at time 1?

**Comment by lcit** [comment]
I see. I have shifted the exponential curves to the left to have the first at t=0.

**Comment by ricber** [comment]
@lcit thank you for the exchange ;)
